# Generated by Django 3.1.2 on 2020-11-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imglink',
        ),
    ]
