# Generated by Django 3.1.1 on 2020-10-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_imglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imglink',
        ),
    ]
