# Generated by Django 3.1.1 on 2020-10-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_imglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imglink',
            field=models.CharField(default='khongco', max_length=200),
            preserve_default=False,
        ),
    ]
