# Generated by Django 3.1.2 on 2020-11-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_imglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recap',
        ),
    ]
